name: ipadown-Secrets

on: 
  workflow_dispatch:
    inputs:
      
      APP_VER_ID:
        description: 'Historical Version ID'
        required: true      
      APPID:
        description: 'App Store ID'
        required: true        
      CODE:
        description: 'Two-factor authentication code'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone IPATool-py repository
        run: git clone https://github.com/srlihg66/ipatool-py.git
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies for IPATool-py
        run: pip install -r ipatool-py/requirements.txt

      - name: Purchase app using IPATool-py
        run: python3 ipatool-py/main.py purchase -e "$APPLE_ID" -i "$APPID" -p "${PASSWORD}${CODE}"
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}  # Use GitHub Secrets for sensitive data
          PASSWORD: ${{ secrets.PASSWORD }}  # Use GitHub Secrets for sensitive data
          APP_VER_ID: ${{ github.event.inputs.APP_VER_ID }}
          APPID: ${{ github.event.inputs.APPID }}
          CODE: ${{ github.event.inputs.CODE }}
   
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: srlihg66/ipatool.js
          path: ipatool.js

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ipatool.js
          mkdir -p app
          npm install

      - name: Run the script
        run: |
          cd ipatool.js
          node main.js
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}  # Use GitHub Secrets for sensitive data
          PASSWORD: ${{ secrets.PASSWORD }}  # Use GitHub Secrets for sensitive data
          APP_VER_ID: ${{ github.event.inputs.APP_VER_ID }}
          APPID: ${{ github.event.inputs.APPID }}
          CODE: ${{ github.event.inputs.CODE }}

      - name: Find and upload .ipa files
        run: |
          mkdir -p ipa_files
          find . -name "*.ipa" -exec cp {} ipa_files/ \;

      - name: Upload .ipa files
        uses: actions/upload-artifact@v2
        with:
          name: ipa-files
          path: ipa_files/*
